.changeset/brave-pots-applaud.md, .changeset/silly-seahorses-double.md, packages/base/src/styles/tokens.json, packages/base/src/styles/tokens/borderRadius.ts, packages/base/src/styles/tokens/hadaTypographies.ts, packages/base/src/styles/tokens/shoplTypographies.ts
=> feature: 토큰 업데이트

package.json, packages/base/src/index.tsx
=> update: husky(pre-commit)

.changeset/config.json, .github/workflows/changesets-workflow.yml, package.json
=> fix: 배포 workflow 수정

.changeset/config.json, turbo.json
=> fix: changesets config

.changeset/config.json, .github/CODEOWNERS, turbo.json
- chore: changeset config 수정
>
=> chore: changeset config 수정

.changeset/afraid-moons-learn.md, packages/base/src/stories/colors.mdx, packages/base/src/utils/extractColors.ts
=> feat: add color palette

.github/CODEOWNERS
=> feat: codeowners

.github/workflows/build-test.yml, .github/workflows/changesets-workflow.yml, .github/workflows/test-changed-packages-workflow.yml, .github/workflows/token-update-workflow.yml, docs/package.json, packages/base/package.json, packages/hada-assets/package.json, packages/shopl-assets/package.json, turbo.json
- remote cache 체크
- type-chcek flow 수정
>
=> feat&fix: change type-check, add remote cache

.changeset/clever-colts-rest.md, packages/base/scripts/generate-tokens.cjs, packages/base/scripts/seperate-tokens.cjs, packages/base/src/styles/global.css, packages/base/src/styles/index.ts, packages/base/src/styles/tokens.ts, vite-project/src/App.tsx, vite-project/src/index.css
=> feature: dropshadow 토큰 생성 코드 추가

.changeset/angry-hounds-fail.md, packages/base/.storybook/preview.tsx, packages/base/src/components/Text/Text.mdx, packages/base/src/components/Text/Text.stories.tsx, packages/base/src/components/Text/Text.styled.ts, packages/base/src/components/Text/Text.tsx, packages/base/src/components/Text/Text.types.ts, packages/base/src/components/Text/index.ts
=> feat: add Text

packages/base/build.js, packages/base/tsconfig.json
- esbuild가 바라보는 tsconfig를 변경했습니다.
>
=> fix: esbuild tsconfig 수정

.github/CODEOWNERS, packages/base/package.json, packages/base/scripts/generate-component.sh, packages/base/src/components/Chip/Chip.mdx, packages/base/src/components/Chip/Chip.stories.tsx, packages/base/src/components/Chip/Chip.styled.ts, packages/base/src/components/Chip/Chip.tsx, packages/base/src/components/Chip/Chip.types.ts, packages/base/src/components/Chip/index.ts, packages/base/src/components/Modal/Modal.stories.tsx, turbo.json
- 컴포넌트 폴더 자동 생성 shell script 추가
- codeowners 프론트엔드 챕터로 변경
>
=> feature: generate-component.sh 추가

.changeset/tame-impalas-deliver.md, packages/base/package.json, packages/base/src/components/Chips/ChipButton/index.ts, packages/base/src/components/Chips/ChipToggle/index.ts, packages/base/src/components/Modal/ModalBody.tsx, packages/base/src/components/Modal/ModalContainer.tsx, pnpm-lock.yaml, test-env/package.json, test-env/src/App.tsx
=> fix: debug modal

.changeset/few-cycles-report.md, packages/base/package.json
`shoplflow/base` 
rollback으로 인한 npm version 불일치로 major version up (0.8.0) 
>
=> Chore: shoplflow/base version up (0.8.0)

.changeset/olive-queens-watch.md, packages/base/src/styles/tokens.json
=> caption_700 추가

.changeset/tough-pots-double.md, packages/base/src/styles/tokens.json
=> 400->font weight medium으로 일괄 변경

.changeset/giant-kings-camp.md, packages/base/src/styles/tokens.json
=> font-weight regular 400->500, medium 500->600으로 변경

.changeset/pink-eels-cough.md, .github/workflows/token-update-workflow.yml, packages/base/src/styles/global.css, packages/base/src/styles/tokens.ts
=> fix: token update workflow

.changeset/spotty-cougars-taste.md, packages/base/package.json
=> feat: update package.json

.changeset/serious-carrots-wink.md, packages/base/package.json, packages/base/tsconfig.json
=> hotfix: require of "react" is not supported 대응

.changeset/cold-yaks-tap.md, packages/base/src/components/Inputs/index.ts
- input을 import할 수 없는 문제를 확인하여 export 경로를 수정했습니다.
>
=> feature: input export 경로 수정

.changeset/shiny-seas-grin.md, .github/workflows/changesets-workflow.yml, .github/workflows/check-changesets-update-note.yml, packages/base/src/styles/global.css, packages/hada-assets/src/icons/generated/index.ts, packages/shopl-assets/src/icons/generated/index.ts
=> update: global.css

.changeset/shaggy-cups-smash.md, packages/base/package.json
=> fix: base 패키지 cjs export 수정

.changeset/good-fans-wink.md, .changeset/polite-bobcats-obey.md, .changeset/stale-goats-tickle.md, packages/base/src/components/Buttons/Button/Button.mdx, packages/base/src/components/Buttons/Button/Button.stories.tsx, packages/base/src/components/Buttons/Button/Button.styled.tsx, packages/base/src/components/Buttons/Button/Button.tsx, packages/base/src/components/Buttons/Button/Button.types.ts, packages/base/src/components/Buttons/IconButton/IconButton.mdx, packages/base/src/components/Buttons/IconButton/IconButton.stories.tsx, packages/base/src/components/Buttons/IconButton/IconButton.styled.ts, packages/base/src/components/Buttons/IconButton/IconButton.tsx, packages/base/src/components/Buttons/IconButton/IconButton.types.ts, packages/base/src/components/Inputs/Input/Input.tsx, packages/base/src/components/Inputs/InputButton/InputButton.stories.tsx, packages/base/src/components/Inputs/InputButton/InputButton.styled.ts, packages/base/src/components/Inputs/InputButton/InputButton.tsx
- Button Solid type color 커스텀 추가
- InputButton Primary, Secondary styleVar 추가
- InputButton Background 컬러 지정
>
=> fix: Button, IconButton styleVars

.changeset/slimy-weeks-destroy.md, .changeset/tasty-queens-yell.md, packages/base/src/components/Chips/ChipButton/ChipButton.styled.ts, packages/hada-assets/src/icons/generated/index.ts, packages/shopl-assets/src/icons/generated/index.ts
=> fix: ChipButton

.changeset/rude-penguins-love.md, .changeset/shaggy-jars-grab.md, .eslintrc.js, packages/base/src/components/Modal/Modal.mdx, packages/base/src/components/Modal/Modal.stories.tsx, packages/base/src/components/Modal/Modal.styled.ts, packages/base/src/components/Modal/Modal.types.ts, packages/base/src/components/Modal/ModalBody.tsx, packages/base/src/components/ScrollArea/ScrollArea.mdx, packages/base/src/components/ScrollArea/ScrollArea.stories.tsx, packages/base/src/components/ScrollArea/ScrollArea.tsx, packages/base/src/components/ScrollArea/ScrollArea.types.ts, packages/base/src/components/ScrollArea/index.ts, packages/base/src/components/index.ts
- modal body align center되지 않는 이슈 수정
- ScrollArea 컴포넌트 추가
>
=> feature&fix: ScrollArea 추가, ModalBody align 이슈 수정

.changeset/orange-knives-care.md, .changeset/silent-dragons-serve.md, packages/base/src/components/Buttons/IconButton/IconButton.styled.ts, packages/base/src/components/Inputs/InputButton/InputButton.styled.ts, packages/base/src/components/Inputs/InputButton/InputButton.tsx, packages/base/src/components/Inputs/InputButton/InputButton.types.ts, packages/base/src/components/Inputs/common/input.styled.ts
- input Button 태그 input으로 변경
- input disabled background 컬러 변경
>
=> fix: inputButton, Input 스타일 수정

.changeset/spotty-experts-accept.md, .changeset/swift-insects-appear.md, packages/base/CHANGELOG.md, packages/base/src/components/Checkbox/Checkbox.mdx, packages/base/src/components/Checkbox/Checkbox.stories.tsx, packages/base/src/components/Checkbox/Checkbox.styled.ts, packages/base/src/components/Checkbox/Checkbox.tsx, packages/base/src/components/Checkbox/Checkbox.types.ts, packages/base/src/components/Checkbox/index.ts, packages/base/src/components/List/List.stories.tsx, packages/base/src/components/Menu/Menu.mdx, packages/base/src/components/Menu/Menu.stories.tsx, packages/base/src/components/Menu/Menu.styled.ts, packages/base/src/components/Menu/Menu.tsx, packages/base/src/components/Menu/Menu.types.ts, packages/base/src/components/Radio/Radio.mdx, packages/base/src/components/Radio/Radio.stories.tsx, packages/base/src/components/Radio/Radio.styled.ts, packages/base/src/components/Radio/Radio.tsx, packages/base/src/components/Radio/Radio.types.ts, packages/base/src/components/Radio/index.ts, packages/utils/src/hooks/useSelect.ts
- menu 컴포넌트 추가
- useSelect의 handleToggleSelect 함수의 기능이 제대로 동작하지 않는 문제 수정
>
=> feat: add Menu, fix useSelect

.changeset/late-cycles-vanish.md, packages/base/src/components/ControlButtons/Radio/Radio.styled.ts, packages/base/src/components/Inputs/Input/Input.stories.tsx, packages/base/src/components/Inputs/Input/Input.styled.tsx, packages/base/src/components/Inputs/Input/Input.tsx
=> feature: input number 타입 추가

packages/base/src/components/List/List.mdx, packages/base/src/components/List/List.tsx
=> fix: list storybook 수정

.changeset/mighty-crabs-run.md, packages/base/src/components/List/List.stories.tsx, packages/base/src/components/Tag/Tag.mdx, packages/base/src/components/Tag/Tag.stories.tsx, packages/base/src/components/Tag/Tag.styled.ts, packages/base/src/components/Tag/Tag.tsx, packages/base/src/components/Tag/Tag.types.ts, packages/base/src/components/Tag/index.ts, packages/base/src/components/index.ts, packages/base/src/utils/getNextColor.ts
=> feature: Tag 컴포넌트 추가

.changeset/empty-stingrays-remember.md, packages/base/src/components/Dropdown/Dropdown.stories.tsx, packages/base/src/components/List/List.stories.tsx, packages/base/src/components/List/List.styled.ts, packages/base/src/components/List/List.types.ts, packages/base/src/components/Menu/Menu.stories.tsx, packages/base/src/components/Menu/Menu.styled.ts, packages/base/src/hooks/useOnToggle.ts, packages/base/src/styles/Box.tsx, packages/base/src/styles/JSONScrollView.tsx, packages/base/src/styles/JSONViewer.tsx
- select 로직을 가진 컴포넌트의 story에 데이터를 미리볼 수 있는 UI를 추가했습니다.
- useOnToggle 선택 로직을 수정했습니다.
>
=> feature: storybook 편의기능 업데이트

.changeset/early-trains-grab.md, packages/base/src/components/Menu/Menu.stories.tsx, packages/base/src/components/Menu/Menu.styled.ts, packages/base/src/components/Menu/Menu.tsx, packages/base/src/components/Menu/Menu.types.ts
=> feature: menu 사이즈 추가

.changeset/shaggy-berries-bake.md, .changeset/slimy-moons-trade.md, .eslintrc.js, docs/next.config.js, docs/pages/index.mdx, packages/base/src/components/Avatar/Avatar.mdx, packages/base/src/components/Avatar/Avatar.tsx, packages/base/src/components/Chips/ChipToggle/ChipToggle.stories.tsx, packages/base/src/components/Chips/ChipToggle/ChipToggle.styled.ts, packages/base/src/components/Chips/ChipToggle/ChipToggle.tsx, packages/base/src/components/index.ts
- ChipToggle `Received 'true' for a non-boolean attribute.` 경고 해결
>
=> fix: Received 'true' for a non-boolean attribute 수정

.changeset/witty-timers-draw.md, packages/base/src/components/Inputs/InputButton/InputButton.tsx
=> fix: InputButton X 버튼 노출 이슈 수정

.changeset/dirty-swans-dance.md, packages/utils/src/hooks/useSelect.ts
=> fix: useSelect Error 케이스 수정

.changeset/short-poets-perform.md, .changeset/silent-planes-pretend.md, packages/base/src/components/Inputs/InputButton/InputButton.tsx, packages/base/src/components/Inputs/InputButton/InputButton.types.ts, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.mdx, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.stories.tsx, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.styled.ts, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.tsx, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.types.ts, packages/base/src/components/Inputs/SelectInputButton/index.ts
=> feature: SelectInputButton 추가

.changeset/fuzzy-tigers-decide.md, packages/base/src/components/Inputs/index.ts
=> fix: SelectInputButton export 누락 이슈 수정

.changeset/two-carrots-remain.md, packages/base/src/components/Stack/Stack.styled.ts, packages/base/src/components/Stack/Stack.types.ts
=> feature: Stack 컴포넌트 max/min, height/width prop 추가

.changeset/hot-mirrors-smell.md, packages/base/src/components/Icon/Icon.mdx, packages/base/src/components/Icon/Icon.stories.tsx, packages/base/src/components/Icon/Icon.styled.ts, packages/base/src/components/Icon/Icon.tsx, packages/base/src/components/Icon/Icon.types.ts
=> feature: Icon dangerouslySetInnerHTML prop 추가

.changeset/popular-dodos-drive.md, packages/base/src/components/Icon/Icon.mdx, packages/base/src/components/Icon/Icon.stories.tsx, packages/base/src/components/Icon/Icon.tsx, packages/base/src/components/Icon/Icon.types.ts
=> fix: Icon HTMLAttributes 추가

.changeset/gold-shirts-report.md, packages/base/src/components/Buttons/IconButton/IconButton.styled.ts, packages/base/src/components/Buttons/IconButton/IconButton.tsx, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.stories.tsx, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.tsx, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.types.ts
=> fix: SelectInputButton value type 수정

.changeset/twelve-dryers-refuse.md, packages/base/src/components/Dropdown/Dropdown.stories.tsx, packages/base/src/components/Dropdown/Dropdown.styled.ts, packages/base/src/components/Popper/Popper.tsx, packages/base/src/portal/PopperPortal.tsx
PopperPortal > style에 position: relative  추가
>
=> style: popper

.changeset/kind-geese-sit.md, .changeset/silver-chefs-crash.md, packages/base/src/components/ControlButtons/Checkbox/Checkbox.styled.ts, packages/base/src/components/ControlButtons/Checkbox/Checkbox.tsx, packages/base/src/components/ControlButtons/MinusButton/MinusButton.tsx, packages/base/src/components/ControlButtons/Radio/Radio.tsx, packages/base/src/components/Menu/Menu.styled.ts
Checkbox Container background-color를 transparent로 변경하였어요!
>
=> style: checkbox

.changeset/brown-coins-call.md, packages/base/src/components/Dropdown/Dropdown.mdx, packages/base/src/components/Dropdown/Dropdown.stories.tsx, packages/base/src/components/Dropdown/Dropdown.types.ts, packages/base/src/components/Dropdown/DropdownButton.tsx
Dropdown value를 string > ReactNode로 변경.
>
=> feature: DropdownButton value 변경

.changeset/gentle-planes-cover.md, packages/base/src/components/ControlButtons/MinusButton/MinusButton.styled.ts
=> fix: minusButton width height 수정

.changeset/lemon-items-tease.md, .changeset/new-scissors-act.md, packages/base/src/components/Dropdown/Dropdown.styled.ts, packages/base/src/components/Icon/Icon.mdx, packages/base/src/components/Icon/Icon.styled.ts, packages/base/src/components/Popper/Popper.tsx
=> fix: popper, dropdown style 수정 

.changeset/seven-timers-fix.md, packages/base/src/components/Dropdown/Dropdown.styled.ts, packages/base/src/components/Icon/Icon.styled.ts, packages/hada-assets/scripts/build-icons.sh, packages/hada-assets/scripts/build-illustrations.sh, packages/shopl-assets/scripts/build-icons.sh, packages/shopl-assets/scripts/build-illustrations.sh, packages/shopl-assets/src/icons/generated/index.ts
=> fix: 생성된 아이콘 사이즈가 고정되는 문제 수정

.changeset/thin-fans-admire.md, packages/base/src/components/Inputs/InputButton/InputButton.mdx, packages/base/src/components/List/List.tsx
list 컴포넌트 Text2Rows 말줄임 처리 추가
>
=> fix: list 컴포넌트 Text2Rows 스타일 수정

.changeset/quiet-readers-draw.md, packages/hada-assets/scripts/build-icons.sh, packages/hada-assets/scripts/build-illustrations.sh, packages/shopl-assets/scripts/build-icons.sh, packages/shopl-assets/scripts/build-illustrations.sh, packages/shopl-assets/src/icons/generated/index.ts
=> fix: 생성된 아이콘의 뷰박스가 누락된 문제 수정

.changeset/neat-coins-act.md, packages/base/src/components/Dropdown/DropdownButton.tsx
DropdownButton > Icon szieVar "S" 명시
아이콘 관련  build script 변경했더니, 아이콘이 전부 확장되어 나타나네요
=> feat: dropdown button

.changeset/hot-coins-train.md, .changeset/rich-rice-deliver.md, .changeset/rude-cows-occur.md, packages/base/src/components/Callout/Callout.styled.ts, packages/base/src/components/Dropdown/DropdownButton.tsx, packages/base/src/components/Modal/Modal.stories.tsx, packages/base/src/components/Modal/Modal.styled.ts, packages/base/src/components/Modal/ModalBody.tsx, packages/base/src/components/Modal/ModalContainer.tsx, packages/base/src/hooks/useViewportSizeObserver.ts, packages/base/src/utils/getNextColor.ts
=> fix: 모달 뷰포트 기반 리사이즈, 컬러 토큰 로직 수정

.changeset/hip-buttons-try.md, .changeset/tidy-oranges-suffer.md, packages/base/src/components/Dropdown/DropdownButton.tsx, packages/base/src/components/Modal/providers/ModalProvider.tsx
feat: 뒤로가기 시, 모달 비워주는 로직 추가 (ModalProvider)
>
=> feat: 뒤로가기 시, 모달 비워주는 로직 추가 (ModalProvider)

.changeset/gorgeous-carrots-love.md, packages/base/src/components/Inputs/Input/Input.tsx
style:  Input DeleteIcon 컬러 변경 (netural600 -> neutarl350)
=> style:  Input DeleteIcon 컬러 변경

.changeset/bright-humans-sing.md, .changeset/config.json, .changeset/friendly-buckets-fry.md, .husky/post-checkout, packages/base/src/components/Dropdown/Dropdown.types.ts, packages/base/src/components/Dropdown/DropdownButton.tsx, packages/base/src/components/Inputs/Input/Input.tsx, packages/base/src/components/Inputs/common/input.styled.ts
=> feat&fix: dropdown, input

.changeset/config.json, .changeset/wise-pugs-cry.md, packages/base/src/components/Inputs/InputButton/InputButton.tsx, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.tsx
=> fix: input minHeight 추가

.changeset/config.json, .changeset/rotten-pans-clean.md, packages/base/src/components/Inputs/Input/Input.styled.tsx
=> fix: input number 타입 스타일 수정

.changeset/config.json, .changeset/silver-jeans-travel.md, .husky/post-checkout, packages/base/src/components/Inputs/Input/Input.tsx, packages/base/src/components/Inputs/Input/utils/getNumberLimiteRange.ts, packages/base/src/components/Inputs/InputButton/InputButton.tsx, packages/base/src/components/Inputs/common/input.styled.ts
=> fix: input wrapper 사이즈 수정

.changeset/config.json, .changeset/fast-dancers-grow.md, packages/base/src/components/Inputs/Input/Input.stories.tsx, packages/base/src/components/Inputs/Input/Input.styled.tsx, packages/base/src/components/Inputs/Input/Input.tsx, packages/base/src/components/Inputs/common/input.styled.ts
=> fix: input default type 수정 

.changeset/stupid-coins-tie.md, packages/base/src/components/Popper/Popper.tsx
Popper >  PopperPortal > FloatingPortal 에서 포탈이 생성되는 DOM이 여러개 생기는 이슈를 수정
>
=> Fix: popper

.changeset/young-vans-confess.md, packages/base/src/components/Popper/Popper.tsx, packages/base/src/components/Popper/usePopper.ts
-  PopperContextType에 useFloating의 모든 리턴 타입을 추가
>
=> Update: Popper

.changeset/fast-bats-work.md, packages/base/CHANGELOG.md, packages/base/package.json, packages/base/src/components/Modal/Modal.styled.ts, packages/base/src/components/Modal/Modal.types.ts, test-env/CHANGELOG.md, test-env/package.json
=> [Feature/add modal size] Modal sizeVar에 XXXL 추가

.changeset/brown-bananas-tap.md, packages/base/src/styles/global.css, packages/base/src/styles/tokens.json, packages/base/src/styles/tokens.ts
=> spacing02, paragraph1, paragraph2 추가

.changeset/famous-snakes-exist.md, packages/base/src/components/Pagination/Pagination.mdx, packages/base/src/components/Pagination/Pagination.stories.tsx, packages/base/src/components/Pagination/Pagination.styled.ts, packages/base/src/components/Pagination/Pagination.tsx, packages/base/src/components/Pagination/Pagination.types.ts, packages/base/src/components/Pagination/PaginationSizeSelector.tsx, packages/base/src/components/Pagination/index.ts
- Pagination Component를 만들었어요!
>
=> feature: Add Pagination Component

.changeset/stale-cameras-search.md, packages/utils/src/hooks/useParentElementClick.ts
fix: useParentElementClick 인수 타입 변경(EventTarget > Event)
>
=> Fix: useParentElementClick

.changeset/twenty-bananas-prove.md, packages/base/CHANGELOG.md, packages/base/package.json, packages/base/src/components/Dropdown/DropdownButton.tsx, packages/extension/CHANGELOG.md, packages/extension/package.json, pnpm-lock.yaml, test-env/CHANGELOG.md, test-env/package.json
`<Dropdown.Button/>` 컴포넌트의 value값이 placeholder와 동일한 스타일링이 적용되도록 `<Text/>` 내부로 변경합니다.
- 관련 이슈 [SH-814](https://shoplworks.atlassian.net/browse/SH-814)
>
[SH-814]: https://shoplworks.atlassian.net/browse/SH-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SH-814] Fix/dropdown button

.changeset/sixty-cougars-work.md, packages/base/src/components/Dropdown/DropdownButton.tsx
- value를 감싸던 Text Component 제거
>
=> update: DropdownButton

.changeset/kind-ligers-laugh.md, packages/base/src/components/Tree/Tree.stories.tsx, packages/base/src/components/Tree/Tree.styled.ts, packages/base/src/components/Tree/Tree.tsx, packages/base/src/components/Tree/Tree.types.ts
-  disabled 속성 추가
- arrowIconButton size 변경
- story docs: 변경사항반영 및 예시 코드 수정
>
=> fix: Tree > disabled 속성 추가 및 사소한 style 변경

.changeset/great-seals-build.md, packages/base/src/components/Tree/Tree.tsx, packages/base/src/components/Tree/Tree.types.ts, packages/extension/public/manifest.json
- disabled일 경우 leftSource 및 onClick event disabled 처리
- disabled 속성이 true일 경우 leftSource도 disabled 처리되도록 수정 
- disabled 속성이 true일 경우 lonClick event 수정
>
=> fix: Tree > disabled 속성에서의 leftSource, onClick event 수정

.changeset/shiny-mice-serve.md, .changeset/smooth-seas-learn.md, packages/base/package.json, packages/base/src/components/ToggleButton/ToggleButton.mdx, packages/base/src/components/ToggleButton/ToggleButton.stories.tsx, packages/base/src/components/ToggleButton/ToggleButton.styled.ts, packages/base/src/components/ToggleButton/ToggleButton.tsx, packages/base/src/components/ToggleButton/ToggleButton.types.ts, packages/base/src/components/ToggleButton/index.ts, packages/base/src/components/ToggleButton/useToggleButton.ts, packages/base/src/components/index.ts, packages/base/src/styles/IconAssets.tsx
- ToggleButton을 만들었어요!
stories, mdx는 추후에 더 디벨롭할 예정입니다!
>
=> feature: ToggleButton

.changeset/early-elephants-yell.md, .changeset/neat-onions-matter.md, .changeset/nervous-comics-sniff.md, .github/workflows/build-test.yml, .github/workflows/changesets-workflow.yml, .github/workflows/check-changesets-update-note.yml, .github/workflows/test-changed-packages-workflow.yml, .github/workflows/token-update-workflow.yml, packages/base/src/components/ToggleButton/ToggleButton.tsx
- ToggleButton type을 지정해주었어요
- Github Action pnpm 설정하는 부분을 수정했어요
>
=> Update: ToggleButton

.changeset/hip-pianos-guess.md, packages/base/src/components/ControlButtons/Checkbox/Checkbox.styled.ts, packages/base/src/components/ControlButtons/Checkbox/Checkbox.tsx, packages/base/src/components/ControlButtons/Checkbox/Checkbox.types.ts
Checkbox를 업데이트 했어요
- forwardRef로 래핑해서 ref를 받을 수 있게 되었습니다!
- 버튼 > 버튼 구조로 발생하는 이슈를 해결 했습니다!
>
=> Update: Checkbox

.changeset/shiny-balloons-clap.md, packages/base/package.json, packages/base/src/components/Inputs/InputButton/InputButton.stories.tsx, packages/base/src/components/Inputs/InputButton/InputButton.tsx, packages/base/src/components/Inputs/InputButton/InputButton.types.ts
- InputButton에 useClear Prop을 추가했어요
- 불필요한 scripts를 제거했어요
>
=> update: InputButton

.changeset/silver-tomatoes-confess.md, packages/shopl-assets/src/icons/assets/ic-required.svg, packages/shopl-assets/src/icons/generated/index.ts
=> update: shopl-assets

.changeset/young-oranges-lie.md, packages/base/src/components/Inputs/Input/Input.tsx, packages/base/src/components/Inputs/Input/Input.types.ts, packages/base/src/components/Inputs/common/input.styled.ts
=> Update: Input Component

.changeset/serious-cooks-walk.md, packages/base/src/components/Datepickers/stepper/Year.styled.tsx, packages/base/src/components/Datepickers/stepper/YearSelect.tsx
-YearSelect(YearStepper)의 스타일을 변경했어요
>
=> Update: YearStepper

.changeset/spicy-queens-love.md, packages/base/src/components/Datepickers/stepper/YearSelect.tsx
- YearSelect의 height를 동적으로 지정하게 변경했어요
>
=> update: YearSelect

.changeset/unlucky-melons-wait.md, packages/base/src/components/Datepickers/DayDatepicker/DayDatepicker.stories.tsx, packages/base/src/components/Datepickers/DayDatepicker/DayDatepicker.tsx, packages/base/src/components/Datepickers/stepper/YearSelect.tsx
- DayDatepicker MonthStepper의 locale 값을 Datepicker와 매핑해주었어요
>
=> Update: DayDatepicker

.changeset/four-students-sort.md, packages/base/src/components/Datepickers/AnnualDatepicker/AnnualDatepicker.stories.tsx, packages/base/src/components/Datepickers/AnnualDatepicker/AnnualDatepicker.styled.ts, packages/base/src/components/Datepickers/AnnualDatepicker/AnnualDatepicker.tsx, packages/base/src/components/Datepickers/AnnualDatepicker/AnnualDatepicker.types.ts
- AnnualDatepicker에 선택 불가능한 년도를 지정할 수 있게 되었어요.
>
=> Update: AnnualDatepicker

.changeset/famous-kids-love.md, packages/base/src/components/Datepickers/MonthDatepicker/MonthDatepicker.styled.ts, packages/base/src/components/Datepickers/MonthDatepicker/MonthDatepicker.tsx, packages/base/src/components/Datepickers/WeekDatepicker/WeekDatepicker.styled.ts
- MonthDatepicker의 선택된 "달"이 잘못 표시되는 버그를 수정했어요
>
=> Fix: MonthDatepicker

.changeset/large-ads-draw.md, packages/base/src/components/Datepickers/MonthDatepicker/MonthDatepicker.styled.ts, packages/base/src/components/Datepickers/WeekDatepicker/WeekDatepicker.styled.ts
=> style: Datepicker

.changeset/few-peas-peel.md, packages/base/src/components/Title/Title.mdx, packages/base/src/components/Title/Title.stories.tsx, packages/base/src/components/Title/Title.styled.ts, packages/base/src/components/Title/Title.tsx, packages/base/src/components/Title/Title.types.ts, packages/base/src/components/Title/index.ts, packages/base/src/components/index.ts
=> feat: Title 컴포넌트 생성

.changeset/twelve-seahorses-hide.md, packages/base/src/components/Inputs/Input/Input.tsx
- Input의 isFocused 값이 변경되는 이벤트를 Blur > Keydown으로 변경했어요
>
=> Update: Input

.changeset/sour-bags-roll.md, packages/base/src/components/Buttons/IconButton/IconButton.tsx
- IconButton type의 기본값을 설정했어요
>
=> Update: IconButton

.changeset/bright-ways-teach.md, packages/base/src/components/Callout/Callout.tsx
- CalloutText의 typography를 paragraph2로 변경했어요
>
=> Update: Callout

.changeset/clever-olives-brush.md, packages/base/src/components/Datepickers/DayDatepicker/DayDatepicker.stories.tsx, packages/base/src/components/Datepickers/DayDatepicker/DayDatepicker.tsx, packages/base/src/components/Datepickers/DayDatepicker/DayDatepicker.types.ts, packages/base/src/components/Datepickers/stepper/MonthStepper.tsx, packages/base/src/components/Datepickers/stepper/YearSelect.tsx, packages/base/src/components/Datepickers/stepper/YearStepper.tsx
update: DayDatepicker에 className를 공유하도록 수정했어요
>
=> Update: datepicker

.changeset/silent-jokes-exercise.md, packages/shopl-assets/src/icons/assets/ic-gradient-doc.svg, packages/shopl-assets/src/icons/generated/index.ts
=> feat: GradientDoc 아이콘 추가

.changeset/chilly-masks-marry.md, packages/base/src/components/Comboboxs/NumberCombobox/NumberCombobox.tsx
- NumberCombobox의 아이콘 방향을 수정했어요
>
=> fix: NumberCombobox

.changeset/chatty-snails-poke.md, packages/base/src/components/Buttons/IconButton/IconButton.stories.tsx, packages/base/src/components/Buttons/IconButton/IconButton.styled.ts
- IconButton 내부의 svg 엘리먼트의 width, heigth을 20px로 고정했어요
>
=> fix: IconButton

.changeset/weak-pigs-work.md, packages/base/src/components/Comboboxs/NumberCombobox/NumberCombobox.tsx, packages/base/src/components/Inputs/InputButton/InputButton.tsx
- NumberCombobox 키보드 이벤트를 업데이트 했어요
>
=> update: NumberCombobox

.changeset/witty-actors-perform.md, packages/shopl-assets/src/icons/assets/ic-excel.svg, packages/shopl-assets/src/icons/generated/index.ts
- shopl-assets에 ic-excel을 추가했어요
>
=> feat: ic-excel 추가

.changeset/good-pumpkins-yawn.md, packages/base/src/components/Buttons/DropdownButton/DropdownButton.mdx, packages/base/src/components/Buttons/DropdownButton/DropdownButton.stories.tsx, packages/base/src/components/Buttons/DropdownButton/DropdownButton.styled.ts, packages/base/src/components/Buttons/DropdownButton/DropdownButton.tsx, packages/base/src/components/Buttons/DropdownButton/DropdownButton.types.ts, packages/base/src/components/Buttons/DropdownButton/index.ts, packages/base/src/components/Buttons/DropdownButton/useDropdownButton.ts, packages/base/src/components/Buttons/index.ts, packages/base/src/components/Dropdown/Dropdown.mdx, packages/base/src/components/Dropdown/Dropdown.styled.ts, packages/base/src/components/Dropdown/Dropdown.tsx, packages/base/src/components/Dropdown/Dropdown.types.ts, packages/base/src/components/Dropdown/DropdownTriggerButton.tsx
- DropdownButton을 만들었어요.
- 컴포넌트 이름이 겹치던 Dropdown의 Button 이름을 변경했어요(DropdownButton -> DropdownTriggerButton)
>
=> feat: DropdownButton 컴포넌트를 만들었어요.

.changeset/seven-otters-beg.md, packages/base/src/components/Buttons/DropdownButton/DropdownButton.styled.ts, packages/base/src/components/Buttons/DropdownButton/DropdownButton.tsx, packages/base/src/components/Buttons/SplitButton/SplitButton.mdx, packages/base/src/components/Buttons/SplitButton/SplitButton.stories.tsx, packages/base/src/components/Buttons/SplitButton/SplitButton.styled.ts, packages/base/src/components/Buttons/SplitButton/SplitButton.tsx, packages/base/src/components/Buttons/SplitButton/SplitButton.types.ts, packages/base/src/components/Buttons/SplitButton/index.ts, packages/base/src/components/Buttons/SplitButton/useSplitButton.ts, packages/base/src/components/Buttons/index.ts, packages/base/src/components/Tooltip/Tooltip.tsx, packages/base/src/styles/utils/getPopoverContentStyle.ts
=> feat: SplitButton

.changeset/neat-chefs-kick.md, packages/base/src/components/Callout/Callout.styled.ts
- Callout Info 배경 neutral100 -> neutral400_5로 수정
>
=> update: Callout Info background neutral100 -> neutral400_5로 수정

.changeset/yellow-fishes-obey.md, packages/base/src/components/Buttons/Button/Button.stories.tsx, packages/base/src/components/Comboboxs/NumberCombobox/NumberCombobox.stories.tsx, packages/base/src/components/Comboboxs/NumberCombobox/NumberCombobox.tsx, packages/base/src/components/Datepickers/AnnualDatepicker/AnnualDatepicker.stories.tsx
- NumberCombobox onKeyDown 핸들러를 업데이트 했어요
>
=> update: Number Combobox Component

.changeset/quick-mirrors-glow.md, packages/base/src/components/Buttons/Button/Button.stories.tsx, packages/base/src/components/Buttons/Button/Button.styled.tsx
- S사이즈 Button gap 변경 (4px -> 2px)
>
=> upate: Button

.changeset/swift-hounds-swim.md, packages/base/src/components/Buttons/Button/Button.mdx, packages/base/src/components/Buttons/Button/Button.stories.tsx, packages/base/src/components/Buttons/DropdownButton/DropdownButton.mdx, packages/base/src/components/Buttons/DropdownButton/DropdownButton.stories.tsx, packages/base/src/components/Buttons/IconButton/IconButton.mdx, packages/base/src/components/Buttons/IconButton/IconButton.stories.tsx, packages/base/src/components/Buttons/SplitButton/SplitButton.mdx, packages/base/src/components/Buttons/SplitButton/SplitButton.stories.tsx
Buttons storybook 문서 업데이트
- Button
- DropdownButton
- IconButton
- SplitButton
**version이 꼬일 것 같아 changeset은 반영하지 않았는데, 리뷰 완료 후 반영해두겠습니다**
>
=> docs: Button,DropdownButton,IconButton,SplitButton 문서 정리

.changeset/little-readers-arrive.md, packages/base/src/components/ControlButtons/Checkbox/Checkbox.mdx, packages/base/src/components/ControlButtons/Checkbox/Checkbox.stories.tsx, packages/base/src/components/ControlButtons/MinusButton/MinusButton.mdx, packages/base/src/components/ControlButtons/MinusButton/MinusButton.stories.tsx, packages/base/src/components/ControlButtons/MinusButton/MinusButton.types.ts, packages/base/src/components/ControlButtons/Radio/Radio.mdx, packages/base/src/components/ControlButtons/Radio/Radio.stories.tsx
Checkbox, MinusButton, Radio 문서 정리
**version이 꼬일 것 같아 changeset은 반영하지 않았는데, 리뷰 완료 후 반영해두겠습니다**
>
=> docs: Checkbox, MinusButton, Radio 문서 정리

.changeset/sweet-badgers-lie.md, packages/templates/src/components/TitleGroup/index.ts
- update: TitleGroup의 default as를 TitleGroup으로 수정
>
=> update: TitleGroup

.changeset/fair-parents-breathe.md
=> add. 할일 관련 아이콘 추가

.changeset/giant-camels-behave.md, packages/base/src/components/Inputs/InputButton/InputButton.tsx, packages/base/src/components/Inputs/InputButton/InputButton.types.ts
input Button에 isError props 추가
>
=> add. input Button에 isError props 추가

.changeset/light-timers-do.md, packages/templates/src/components/TitleGroup/TitleGroup.stories.tsx, packages/templates/src/components/TitleGroup/TitleGroup.tsx, packages/templates/src/components/TitleGroup/TitleGroup.types.ts
=> update: TitleGroup 컴포넌트

.changeset/unlucky-kings-wash.md, packages/base/src/components/Tabs/Tabs.styled.ts
-  Tab styleVar='INFO' 스타일 조정
>
=> update: tabs

.changeset/fuzzy-mangos-exercise.md, packages/base/src/components/Modal/ModalBody.tsx, packages/base/src/components/ScrollArea/ScrollArea.tsx
=> fix: ModalBody max height

.changeset/nice-fireants-camp.md, packages/base/src/components/Modal/ModalBody.tsx
=> fix: ModalBodyContent Maxheight

.changeset/shy-rivers-sing.md, packages/base/src/components/Dropdown/Dropdown.stories.tsx, packages/base/src/components/Dropdown/Dropdown.types.ts, packages/base/src/components/Dropdown/DropdownTriggerButton.styled.ts, packages/base/src/components/Inputs/InputButton/InputButton.styled.ts, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.tsx, packages/base/src/components/ToggleButton/ToggleButton.stories.tsx, packages/base/src/components/ToggleButton/ToggleButton.styled.ts, packages/base/src/components/ToggleButton/ToggleButton.tsx
- Toggle Button : selected-disabled 스타일링 추가
- Dropdown Trigger Button : disabled 속성일 때 background-color 수정
>
=> update: Toggle Button, Dropdown Trigger Button, InputButton의 disabled 스타일링 수정

.changeset/lemon-ants-sleep.md, packages/base/src/components/Tree/Tree.stories.tsx, packages/base/src/components/Tree/Tree.styled.ts, packages/base/src/components/Tree/Tree.tsx, packages/shopl-assets/src/icons/assets/ic-right-arrow-solid-xsmall.svg, packages/shopl-assets/src/icons/generated/index.ts
=> update: Tree Component

.changeset/orange-pumpkins-pay.md, packages/base/src/components/Skeleton/Skeleton.mdx, packages/base/src/components/Skeleton/Skeleton.stories.tsx, packages/base/src/components/Skeleton/Skeleton.styled.ts, packages/base/src/components/Skeleton/Skeleton.tsx, packages/base/src/components/Skeleton/Skeleton.types.ts, packages/base/src/components/Skeleton/index.ts, packages/base/src/components/index.ts
- styleVar: 'circle' | 'rectangle'로 스타일 변경 가능
- width와 height만을 props로 받아와 크기 조정
- styleVar: 'circle' | 'rectangle'중 선택해서 skeleton 모양 변경
- width와 height만을 props로 받아와 사이즈 조정
>
=> feat: Skeleton 컴포넌트 생성

.changeset/funny-feet-shave.md, packages/base/src/components/Inputs/TextArea/TextArea.tsx
- TextArea에 gap을 삭제했습니다.
[#SH-9991](https://shoplworks.atlassian.net/browse/SH-9991)
>
=> update: TextArea gap 삭제

.changeset/polite-dogs-cross.md, packages/base/src/components/Slider/Slider.mdx, packages/base/src/components/Slider/Slider.stories.tsx, packages/base/src/components/Slider/Slider.styled.ts, packages/base/src/components/Slider/Slider.tsx, packages/base/src/components/Slider/Slider.types.ts, packages/base/src/components/Slider/SliderSteps.tsx, packages/base/src/components/Slider/SliderThumbs.tsx, packages/base/src/components/Slider/index.ts, packages/base/src/components/Slider/sliderUtils.ts, packages/base/src/components/Slider/useSlider.ts, packages/base/src/components/index.ts
[SH-9912](https://shoplworks.atlassian.net/browse/SH-9912)
```
Slider
├── SliderContainer (disabled 스타일링이 적용된 wrapper)
└── SliderTrack (클릭 가능한 트랙)
├── SliderSteps (증분 단위에 따른 단위 표시 (SliderTrack과 동일한 색상))
├── SelectedTrack (선택된 범위 영역)
└── SliderThumbs (드래그 가능한 핸들)
```
관심사를 나누기 위해 아래와 같이 분리했습니다.
- `Slider` : 렌더링만 담당
- `sliderUtils` :  단순 계산 로직 (thumb button의 위치 percent 계산)
- `useSlider` hook :  상태(선택 범위) 및 이벤트 처리(드래깅 등) 로직
>
[SH-9912]: https://shoplworks.atlassian.net/browse/SH-9912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Slider 컴포넌트 추가

.changeset/gentle-kids-end.md, packages/base/src/components/Slider/Slider.stories.tsx, packages/base/src/components/Slider/SliderThumbs.tsx, packages/base/src/components/Slider/useSlider.ts
- thumb 버튼에 button type을 설정해 form 내부에서 사용했을 때 submit되는 문제를 해결했어요
- 트랙을 클릭해서 범위를 설정할 경우 closer에 캡쳐된 값을 사용하는 문제를 수정했어요
- storybook에서 설정한 범위를 볼 수 있도록 story문서를 보완했어요
>
=> update: Slider 수정

.changeset/spotty-socks-complain.md, .github/workflows/icon-automation.yml, packages/shopl-assets/scripts/add-icon-changeset.js
- 새로운 GitHub Actions 워크플로우를 추가하여 아이콘을 자동으로 빌드하고 린트합니다.
>
=> feat: 아이콘 자동화 워크플로우 추가

.changeset/red-ears-give.md, packages/base/src/components/Dropdown/DropdownTriggerButton.styled.ts
=> update: Dropdown L 사이즈 스타일 조정

.changeset/twelve-birds-tan.md, packages/base/src/components/Datepickers/MonthDatepicker/MonthDatepicker.tsx, packages/base/src/components/Datepickers/WeekDatepicker/WeekDatepicker.tsx
[SH-9834](https://shoplworks.atlassian.net/browse/SH-9834)
- 주별/월별 DatePicker > maxDate가 있을 경우 선택 가능 범위 수정
>
[SH-9834]: https://shoplworks.atlassian.net/browse/SH-9834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update: 주별/월별 DatePicker > maxDate가 있을 경우 선택 가능 범위 수정

.changeset/little-birds-decide.md, packages/base/src/components/Dropdown/DropdownTriggerButton.styled.ts
=> update(style): DropdownTriggerButton L size

packages/base/src/styles/global.css, packages/base/src/styles/tokens.json, packages/hada-assets/src/icons/generated/index.ts, packages/hada-assets/src/illustrations/generated/index.ts, packages/shopl-assets/src/icons/generated/index.ts, packages/shopl-assets/src/illustrations/generated/index.ts
hada paragraph1, paragraph2 추가
>
=> hada paragraph1, paragraph2 추가

.changeset/dirty-moles-ring.md, .changeset/thick-coats-carry.md, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.mdx, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.stories.tsx, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.styled.ts, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.tsx, packages/base/src/components/Inputs/SelectInputButton/SelectInputButton.types.ts
SelectInputButton sizeVar 추가 및 story문서 수정
>
=> update: SelectInputButton sizeVar 추가 및 story문서 수정

.changeset/unlucky-rabbits-hang.md, packages/base/src/components/Buttons/Button/Button.styled.tsx, packages/base/src/components/ControlButtons/Checkbox/Checkbox.styled.ts
HADA에서 사용하는 Button(secondary), Checkbox 컴포넌트 스타일 변경
>
=> update: Button, Checkbox 스타일 수정

.changeset/odd-mugs-add.md, packages/utils/src/hooks/index.ts, packages/utils/src/hooks/usePopover.ts
HADA에서도 Popover의 상태를 독립적으로 관리해야 한다는 요구사항이 있어 `@shoplflow/utils`에 `usePopover` hook을 추가했습니다.
JsDoc으로 예시 코드를 적어두었는데 이해가 잘 가지 않는 부분은 알려주세요! 
>
=> feat: usePopover hook 추가

.changeset/nasty-parrots-cry.md, packages/base/src/components/Buttons/Button/Button.stories.tsx, packages/base/src/components/Buttons/Button/Button.styled.tsx, packages/base/src/components/Buttons/Button/Button.tsx, packages/base/src/components/Buttons/Button/Button.types.ts
- 버튼 컴포넌트에 'XS' sizeVar 추가
- 버튼의 스타일에 'XS' 크기 관련 스타일 변경
>
=> update: 버튼 컴포넌트에 'XS' 사이즈 추가

.changeset/gold-parents-pay.md, packages/templates/src/components/Table/components/Table/TableMain/FixedTable.tsx
=> fix(Table): 테이블 헤더와 바디 스크롤 동기화 문제 수정

.changeset/quiet-seahorses-kiss.md, packages/base/src/components/SearchBar/SearchBar.stories.tsx, packages/base/src/components/SearchBar/SearchBar.types.ts, packages/base/src/components/SearchBar/SearchBarInput.tsx
- SearchBar maxLength 추가 
- 내부에서 number 타입도 string으로 변환하는 로직 삭제 
- onChange 조작 가능하도록 수정
>
=> update: SearchBar maxLength props 추가

.changeset/metal-waves-deny.md, packages/base/src/components/Avatar/Avatar.stories.tsx, packages/base/src/components/Avatar/Avatar.tsx
=> update: Avatar onError props 추가
